// src/engineClient.ts
//
// Getting the search off the main thread.
//
// A native NextOS app is compiled to ONE module - there is no second
// entry point to hand a Worker - so the worker's source is a four-line
// module built at run time that imports this app's own build/app.js (read
// from the app's directory in the VFS, wrapped in a blob: URL) and calls
// the `runEngineWorker` the default export carries. Worker and window
// therefore run the identical rules, evaluation and search: there is no
// second copy of anything to drift.
//
// The prelude before that import exists because the bundle's module
// graph resolves react and @kumin/sdk through `window.__kuminSdk`, and a
// worker has no window. Stubbing them is enough precisely because no
// module in this app touches React or the SDK at import time - the
// components are only DEFINED at module scope, never called - so the
// bundle evaluates cleanly and `runEngineWorker` is reached.
//
// If a Worker cannot be created at all (a strict content policy, an
// ancient browser, a blob: URL that will not import), `fallback` runs
// the same iterative deepening on the main thread one depth at a time,
// yielding to the browser between depths so the interface still paints.

import type { Position } from './lib/types';
import type { SearchInfo, SearchOptions } from './lib/engine';
import { searchChunked } from './lib/engine';
import { toFen } from './lib/fen';
import { toUci } from './lib/san';
import { movesTo } from './lib/game';
import type { GameTree } from './lib/game';

export interface EngineUpdate {
  depth: number;
  seldepth: number;
  score: number;
  mate: number | null;
  /** The principal variation in UCI - the caller turns it into SAN
   *  against the position it asked about. */
  pv: string[];
  bestMove: string;
  nodes: number;
  timeMs: number;
  nps: number;
  fromBook: boolean;
  /** 'worker' or 'main' - shown in the engine panel, because "why is
   *  this slow?" deserves an answer. */
  where: 'worker' | 'main';
}

export interface EngineRequest {
  position: Position;
  /** The game the position came from, so the search sees the same
   *  repetition history. Optional. */
  tree?: GameTree;
  nodeId?: number;
  options: Omit<SearchOptions, 'onInfo' | 'shouldStop' | 'random' | 'now'>;
  onInfo?: (update: EngineUpdate) => void;
}

type BundleReader = () => Promise<string | null>;

const WORKER_PRELUDE = `
// Generated by the Chess app. Runs its own bundle inside a Worker.
self.window = self;
var noop = function () { return null; };
self.__kuminSdk = {
  react: { createElement: noop, Fragment: 'div', memo: function (c) { return c; }, forwardRef: function (c) { return c; }, createContext: function () { return {}; }, useState: noop, useEffect: noop, useMemo: noop, useCallback: noop, useRef: noop },
  reactDom: { createRoot: noop, render: noop },
  reactJsxRuntime: { jsx: noop, jsxs: noop, Fragment: 'div' },
  zustand: { create: function () { return function () { return {}; }; } },
  sdk: function () {
    var reject = function () { return Promise.reject(new Error('not available in the engine worker')); };
    return {
      app: { id: 'chess', dir: '' },
      getVfs: function () { return null; },
      storage: { get: noop, set: noop, remove: noop },
      notify: reject,
      events: { subscribe: function () { return noop; }, emit: noop },
      theme: { useIsDark: function () { return false; }, tokens: function () { return { isDark: false, accentColor: '#000' }; } },
      assistant: { ask: reject },
      agents: { run: reject, waitForRun: reject },
      registerTool: function () { return noop; },
      openApp: noop,
      dispatchIntent: reject,
      fs: { edit: reject, patch: reject },
      db: {},
      useWindows: function () { return { windows: [], activeWindowId: null }; }
    };
  }
};
// Messages that arrive before the bundle has finished importing are
// queued, not lost.
var pending = [];
self.onmessage = function (event) { pending.push(event); };
import(BUNDLE_URL)
  .then(function (module) {
    var entry = module.default && module.default.runEngineWorker;
    if (typeof entry !== 'function') throw new Error('the bundle has no engine worker entry');
    entry(self);
    var queued = pending;
    pending = [];
    for (var i = 0; i < queued.length; i++) self.onmessage(queued[i]);
  })
  .catch(function (error) {
    self.postMessage({ type: 'fatal', message: String(error && error.message ? error.message : error) });
  });
`;

export class EngineClient {
  private worker: Worker | null = null;
  private bundleUrl: string | null = null;
  private workerUrl: string | null = null;
  private readonly readBundle: BundleReader;
  private nextId = 1;
  private pending: {
    id: number;
    resolve: (update: EngineUpdate) => void;
    onInfo?: (update: EngineUpdate) => void;
  } | null = null;
  private starting: Promise<Worker | null> | null = null;
  private disabled = false;
  private fallbackTimer: ReturnType<typeof setTimeout> | null = null;
  /** Set when the worker could not be created, so the panel can say so. */
  public lastError: string | null = null;

  constructor(readBundle: BundleReader) {
    this.readBundle = readBundle;
  }

  /** True once a real Worker is running. */
  get usingWorker(): boolean {
    return this.worker !== null;
  }

  private async start(): Promise<Worker | null> {
    if (this.worker) return this.worker;
    if (this.disabled) return null;
    if (this.starting) return this.starting;
    this.starting = (async () => {
      try {
        if (typeof Worker === 'undefined' || typeof URL.createObjectURL !== 'function') {
          this.disabled = true;
          this.lastError = 'This browser cannot create a Web Worker.';
          return null;
        }
        const code = await this.readBundle();
        if (!code) {
          this.disabled = true;
          this.lastError = "The app's compiled bundle could not be read, so the search runs on the main thread.";
          return null;
        }
        this.bundleUrl = URL.createObjectURL(new Blob([code], { type: 'text/javascript' }));
        const source = WORKER_PRELUDE.replace('BUNDLE_URL', JSON.stringify(this.bundleUrl));
        this.workerUrl = URL.createObjectURL(new Blob([source], { type: 'text/javascript' }));
        const worker = new Worker(this.workerUrl, { type: 'module' });
        worker.onmessage = (event: MessageEvent) => this.onMessage(event.data);
        worker.onerror = () => {
          this.lastError = 'The engine worker stopped; the search moved to the main thread.';
          this.teardown();
          this.disabled = true;
        };
        this.worker = worker;
        return worker;
      } catch (error) {
        this.disabled = true;
        this.lastError = error instanceof Error ? error.message : String(error);
        return null;
      } finally {
        this.starting = null;
      }
    })();
    return this.starting;
  }

  private onMessage(data: unknown): void {
    const message = data as { type?: string; id?: number; message?: string } & Partial<EngineUpdate>;
    if (!message || typeof message !== 'object') return;
    if (message.type === 'fatal') {
      this.lastError = message.message ?? 'The engine worker failed to start.';
      this.teardown();
      this.disabled = true;
      return;
    }
    const waiting = this.pending;
    if (!waiting || message.id !== waiting.id) return;
    const update: EngineUpdate = {
      depth: message.depth ?? 0,
      seldepth: message.seldepth ?? 0,
      score: message.score ?? 0,
      mate: message.mate ?? null,
      pv: message.pv ?? [],
      bestMove: message.bestMove ?? '',
      nodes: message.nodes ?? 0,
      timeMs: message.timeMs ?? 0,
      nps: message.nps ?? 0,
      fromBook: message.fromBook ?? false,
      where: 'worker',
    };
    if (message.type === 'info') {
      waiting.onInfo?.(update);
      return;
    }
    this.pending = null;
    waiting.resolve(update);
  }

  /** Asks for a move. Only one search runs at a time: asking again
   *  cancels the one in flight, which is what the interface wants every
   *  time the user clicks ahead of the engine. */
  async think(request: EngineRequest): Promise<EngineUpdate> {
    this.stop();
    const worker = await this.start();
    if (!worker) return this.thinkOnMainThread(request);
    const id = this.nextId++;
    const history =
      request.tree && request.nodeId !== undefined ? movesTo(request.tree, request.nodeId).map((m) => toUci(m)) : [];
    const startFen = request.tree && request.nodeId !== undefined ? request.tree.startFen : toFen(request.position);
    return new Promise<EngineUpdate>((resolve) => {
      this.pending = { id, resolve, onInfo: request.onInfo };
      worker.postMessage({
        type: 'search',
        id,
        fen: startFen,
        history,
        options: { ...request.options },
      });
    });
  }

  /** The no-worker path: one depth per macrotask, so the browser gets a
   *  frame between them and the board never freezes. */
  private thinkOnMainThread(request: EngineRequest): Promise<EngineUpdate> {
    return new Promise<EngineUpdate>((resolve) => {
      const runner = searchChunked(request.position, request.options);
      let last: SearchInfo | null = null;
      const step = (): void => {
        this.fallbackTimer = null;
        const info = runner.next();
        if (info) {
          last = info;
          request.onInfo?.(toUpdate(info, 'main'));
          this.fallbackTimer = setTimeout(step, 0);
          return;
        }
        resolve(toUpdate(last ?? runner.best(), 'main'));
      };
      this.fallbackTimer = setTimeout(step, 0);
    });
  }

  /** Stops whatever is running. A worker cannot be interrupted mid
   *  search - it is busy, so it will not see a message - so stopping
   *  means terminating it; the next search starts a fresh one, which
   *  costs a few milliseconds and is the only honest way to do it. */
  stop(): void {
    if (this.fallbackTimer !== null) {
      clearTimeout(this.fallbackTimer);
      this.fallbackTimer = null;
    }
    if (this.pending) {
      const waiting = this.pending;
      this.pending = null;
      if (this.worker) {
        this.worker.terminate();
        this.worker = null;
      }
      waiting.resolve({
        depth: 0,
        seldepth: 0,
        score: 0,
        mate: null,
        pv: [],
        bestMove: '',
        nodes: 0,
        timeMs: 0,
        nps: 0,
        fromBook: false,
        where: this.worker ? 'worker' : 'main',
      });
    }
  }

  private teardown(): void {
    if (this.worker) {
      this.worker.terminate();
      this.worker = null;
    }
  }

  dispose(): void {
    this.stop();
    this.teardown();
    if (this.bundleUrl) URL.revokeObjectURL(this.bundleUrl);
    if (this.workerUrl) URL.revokeObjectURL(this.workerUrl);
    this.bundleUrl = null;
    this.workerUrl = null;
  }
}

function toUpdate(info: SearchInfo, where: 'worker' | 'main'): EngineUpdate {
  return {
    depth: info.depth,
    seldepth: info.seldepth,
    score: info.score,
    mate: info.mate,
    pv: info.pv.map((m) => toUci(m)),
    bestMove: info.bestMove ? toUci(info.bestMove) : '',
    nodes: info.nodes,
    timeMs: info.timeMs,
    nps: info.nps,
    fromBook: info.fromBook,
    where,
  };
}
